#!/bin/bash

VM=$1
SERVER=$2
VIRT_ADDR="/home/${USER}/vm-utils/virt-addr.pl"

if [[ "${SERVER}" != "" ]]; then
    IP=`${VIRT_ADDR} $1 $SERVER`
else
    IP=`${VIRT_ADDR} $1 | sed '1q;d'`
fi

echo "Connecting to $1 with IP: $IP"

screen -h 1000 -t $1 -S $1 ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@$IP
